/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BecomeAPartnerRouteImport } from './routes/become-a-partner'
import { Route as BusinessFinancingRouteImport } from './routes/business-financing'
import { Route as BuyNowGetProtectedPayLaterRouteImport } from './routes/buy-now-get-protected-pay-later'
import { Route as CustomerLoginRouteImport } from './routes/customer-login'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FixNowGetProtectedPayLaterRouteImport } from './routes/fix-now-get-protected-pay-later'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerLoginRouteImport } from './routes/partner-login'
import { Route as PartnerStoresRouteImport } from './routes/partner-stores'
import { Route as PhoneInsuranceNigeriaRouteImport } from './routes/phone-insurance-nigeria'
import { Route as PhoneProtectionRouteImport } from './routes/phone-protection'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProtectionCalculatorRouteImport } from './routes/protection-calculator'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SupportedDevicesRouteImport } from './routes/supported-devices'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PartnerStoresIndexRouteImport } from './routes/partner-stores.index'
import { Route as SupportedDevicesIndexRouteImport } from './routes/supported-devices.index'
import { Route as SupportedDevicesBrandModelRouteImport } from './routes/supported-devices.$brand.$model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerRoute = BecomeAPartnerRouteImport.update({
  id: '/become-a-partner',
  path: '/become-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessFinancingRoute = BusinessFinancingRouteImport.update({
  id: '/business-financing',
  path: '/business-financing',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyNowGetProtectedPayLaterRoute =
  BuyNowGetProtectedPayLaterRouteImport.update({
    id: '/buy-now-get-protected-pay-later',
    path: '/buy-now-get-protected-pay-later',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer-login',
  path: '/customer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FixNowGetProtectedPayLaterRoute =
  FixNowGetProtectedPayLaterRouteImport.update({
    id: '/fix-now-get-protected-pay-later',
    path: '/fix-now-get-protected-pay-later',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner-login',
  path: '/partner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerStoresRoute = PartnerStoresRouteImport.update({
  id: '/partner-stores',
  path: '/partner-stores',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneInsuranceNigeriaRoute = PhoneInsuranceNigeriaRouteImport.update({
  id: '/phone-insurance-nigeria',
  path: '/phone-insurance-nigeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneProtectionRoute = PhoneProtectionRouteImport.update({
  id: '/phone-protection',
  path: '/phone-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionCalculatorRoute = ProtectionCalculatorRouteImport.update({
  id: '/protection-calculator',
  path: '/protection-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportedDevicesRoute = SupportedDevicesRouteImport.update({
  id: '/supported-devices',
  path: '/supported-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerStoresIndexRoute = PartnerStoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerStoresRoute,
} as any)
const SupportedDevicesIndexRoute = SupportedDevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportedDevicesRoute,
} as any)
const SupportedDevicesBrandModelRoute =
  SupportedDevicesBrandModelRouteImport.update({
    id: '/$brand/$model',
    path: '/$brand/$model',
    getParentRoute: () => SupportedDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/business-financing': typeof BusinessFinancingRoute
  '/buy-now-get-protected-pay-later': typeof BuyNowGetProtectedPayLaterRoute
  '/customer-login': typeof CustomerLoginRoute
  '/faqs': typeof FaqsRoute
  '/fix-now-get-protected-pay-later': typeof FixNowGetProtectedPayLaterRoute
  '/login': typeof LoginRoute
  '/partner-login': typeof PartnerLoginRoute
  '/partner-stores': typeof PartnerStoresRouteWithChildren
  '/phone-insurance-nigeria': typeof PhoneInsuranceNigeriaRoute
  '/phone-protection': typeof PhoneProtectionRoute
  '/privacy': typeof PrivacyRoute
  '/protection-calculator': typeof ProtectionCalculatorRoute
  '/support': typeof SupportRoute
  '/supported-devices': typeof SupportedDevicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/partner-stores/': typeof PartnerStoresIndexRoute
  '/supported-devices/': typeof SupportedDevicesIndexRoute
  '/supported-devices/$brand/$model': typeof SupportedDevicesBrandModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/business-financing': typeof BusinessFinancingRoute
  '/buy-now-get-protected-pay-later': typeof BuyNowGetProtectedPayLaterRoute
  '/customer-login': typeof CustomerLoginRoute
  '/faqs': typeof FaqsRoute
  '/fix-now-get-protected-pay-later': typeof FixNowGetProtectedPayLaterRoute
  '/login': typeof LoginRoute
  '/partner-login': typeof PartnerLoginRoute
  '/phone-insurance-nigeria': typeof PhoneInsuranceNigeriaRoute
  '/phone-protection': typeof PhoneProtectionRoute
  '/privacy': typeof PrivacyRoute
  '/protection-calculator': typeof ProtectionCalculatorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/partner-stores': typeof PartnerStoresIndexRoute
  '/supported-devices': typeof SupportedDevicesIndexRoute
  '/supported-devices/$brand/$model': typeof SupportedDevicesBrandModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/business-financing': typeof BusinessFinancingRoute
  '/buy-now-get-protected-pay-later': typeof BuyNowGetProtectedPayLaterRoute
  '/customer-login': typeof CustomerLoginRoute
  '/faqs': typeof FaqsRoute
  '/fix-now-get-protected-pay-later': typeof FixNowGetProtectedPayLaterRoute
  '/login': typeof LoginRoute
  '/partner-login': typeof PartnerLoginRoute
  '/partner-stores': typeof PartnerStoresRouteWithChildren
  '/phone-insurance-nigeria': typeof PhoneInsuranceNigeriaRoute
  '/phone-protection': typeof PhoneProtectionRoute
  '/privacy': typeof PrivacyRoute
  '/protection-calculator': typeof ProtectionCalculatorRoute
  '/support': typeof SupportRoute
  '/supported-devices': typeof SupportedDevicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/partner-stores/': typeof PartnerStoresIndexRoute
  '/supported-devices/': typeof SupportedDevicesIndexRoute
  '/supported-devices/$brand/$model': typeof SupportedDevicesBrandModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-partner'
    | '/business-financing'
    | '/buy-now-get-protected-pay-later'
    | '/customer-login'
    | '/faqs'
    | '/fix-now-get-protected-pay-later'
    | '/login'
    | '/partner-login'
    | '/partner-stores'
    | '/phone-insurance-nigeria'
    | '/phone-protection'
    | '/privacy'
    | '/protection-calculator'
    | '/support'
    | '/supported-devices'
    | '/terms'
    | '/partner-stores/'
    | '/supported-devices/'
    | '/supported-devices/$brand/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-partner'
    | '/business-financing'
    | '/buy-now-get-protected-pay-later'
    | '/customer-login'
    | '/faqs'
    | '/fix-now-get-protected-pay-later'
    | '/login'
    | '/partner-login'
    | '/phone-insurance-nigeria'
    | '/phone-protection'
    | '/privacy'
    | '/protection-calculator'
    | '/support'
    | '/terms'
    | '/partner-stores'
    | '/supported-devices'
    | '/supported-devices/$brand/$model'
  id:
    | '__root__'
    | '/'
    | '/become-a-partner'
    | '/business-financing'
    | '/buy-now-get-protected-pay-later'
    | '/customer-login'
    | '/faqs'
    | '/fix-now-get-protected-pay-later'
    | '/login'
    | '/partner-login'
    | '/partner-stores'
    | '/phone-insurance-nigeria'
    | '/phone-protection'
    | '/privacy'
    | '/protection-calculator'
    | '/support'
    | '/supported-devices'
    | '/terms'
    | '/partner-stores/'
    | '/supported-devices/'
    | '/supported-devices/$brand/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeAPartnerRoute: typeof BecomeAPartnerRoute
  BusinessFinancingRoute: typeof BusinessFinancingRoute
  BuyNowGetProtectedPayLaterRoute: typeof BuyNowGetProtectedPayLaterRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  FaqsRoute: typeof FaqsRoute
  FixNowGetProtectedPayLaterRoute: typeof FixNowGetProtectedPayLaterRoute
  LoginRoute: typeof LoginRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerStoresRoute: typeof PartnerStoresRouteWithChildren
  PhoneInsuranceNigeriaRoute: typeof PhoneInsuranceNigeriaRoute
  PhoneProtectionRoute: typeof PhoneProtectionRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectionCalculatorRoute: typeof ProtectionCalculatorRoute
  SupportRoute: typeof SupportRoute
  SupportedDevicesRoute: typeof SupportedDevicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner': {
      id: '/become-a-partner'
      path: '/become-a-partner'
      fullPath: '/become-a-partner'
      preLoaderRoute: typeof BecomeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-financing': {
      id: '/business-financing'
      path: '/business-financing'
      fullPath: '/business-financing'
      preLoaderRoute: typeof BusinessFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-now-get-protected-pay-later': {
      id: '/buy-now-get-protected-pay-later'
      path: '/buy-now-get-protected-pay-later'
      fullPath: '/buy-now-get-protected-pay-later'
      preLoaderRoute: typeof BuyNowGetProtectedPayLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-login': {
      id: '/customer-login'
      path: '/customer-login'
      fullPath: '/customer-login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix-now-get-protected-pay-later': {
      id: '/fix-now-get-protected-pay-later'
      path: '/fix-now-get-protected-pay-later'
      fullPath: '/fix-now-get-protected-pay-later'
      preLoaderRoute: typeof FixNowGetProtectedPayLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-login': {
      id: '/partner-login'
      path: '/partner-login'
      fullPath: '/partner-login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-stores': {
      id: '/partner-stores'
      path: '/partner-stores'
      fullPath: '/partner-stores'
      preLoaderRoute: typeof PartnerStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-insurance-nigeria': {
      id: '/phone-insurance-nigeria'
      path: '/phone-insurance-nigeria'
      fullPath: '/phone-insurance-nigeria'
      preLoaderRoute: typeof PhoneInsuranceNigeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-protection': {
      id: '/phone-protection'
      path: '/phone-protection'
      fullPath: '/phone-protection'
      preLoaderRoute: typeof PhoneProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-calculator': {
      id: '/protection-calculator'
      path: '/protection-calculator'
      fullPath: '/protection-calculator'
      preLoaderRoute: typeof ProtectionCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supported-devices': {
      id: '/supported-devices'
      path: '/supported-devices'
      fullPath: '/supported-devices'
      preLoaderRoute: typeof SupportedDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-stores/': {
      id: '/partner-stores/'
      path: '/'
      fullPath: '/partner-stores/'
      preLoaderRoute: typeof PartnerStoresIndexRouteImport
      parentRoute: typeof PartnerStoresRoute
    }
    '/supported-devices/': {
      id: '/supported-devices/'
      path: '/'
      fullPath: '/supported-devices/'
      preLoaderRoute: typeof SupportedDevicesIndexRouteImport
      parentRoute: typeof SupportedDevicesRoute
    }
    '/supported-devices/$brand/$model': {
      id: '/supported-devices/$brand/$model'
      path: '/$brand/$model'
      fullPath: '/supported-devices/$brand/$model'
      preLoaderRoute: typeof SupportedDevicesBrandModelRouteImport
      parentRoute: typeof SupportedDevicesRoute
    }
  }
}

interface PartnerStoresRouteChildren {
  PartnerStoresIndexRoute: typeof PartnerStoresIndexRoute
}

const PartnerStoresRouteChildren: PartnerStoresRouteChildren = {
  PartnerStoresIndexRoute: PartnerStoresIndexRoute,
}

const PartnerStoresRouteWithChildren = PartnerStoresRoute._addFileChildren(
  PartnerStoresRouteChildren,
)

interface SupportedDevicesRouteChildren {
  SupportedDevicesIndexRoute: typeof SupportedDevicesIndexRoute
  SupportedDevicesBrandModelRoute: typeof SupportedDevicesBrandModelRoute
}

const SupportedDevicesRouteChildren: SupportedDevicesRouteChildren = {
  SupportedDevicesIndexRoute: SupportedDevicesIndexRoute,
  SupportedDevicesBrandModelRoute: SupportedDevicesBrandModelRoute,
}

const SupportedDevicesRouteWithChildren =
  SupportedDevicesRoute._addFileChildren(SupportedDevicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeAPartnerRoute: BecomeAPartnerRoute,
  BusinessFinancingRoute: BusinessFinancingRoute,
  BuyNowGetProtectedPayLaterRoute: BuyNowGetProtectedPayLaterRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  FaqsRoute: FaqsRoute,
  FixNowGetProtectedPayLaterRoute: FixNowGetProtectedPayLaterRoute,
  LoginRoute: LoginRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerStoresRoute: PartnerStoresRouteWithChildren,
  PhoneInsuranceNigeriaRoute: PhoneInsuranceNigeriaRoute,
  PhoneProtectionRoute: PhoneProtectionRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectionCalculatorRoute: ProtectionCalculatorRoute,
  SupportRoute: SupportRoute,
  SupportedDevicesRoute: SupportedDevicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
